# Generated by Django 3.2.8 on 2021-10-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35, null=True)),
                ('telegram_id', models.IntegerField(default=0, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(default='user', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('right', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=120, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.test')),
            ],
        ),
    ]
