# Generated by Django 3.2.8 on 2021-10-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.test'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='var',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
